# Generated by Django 4.1.6 on 2023-02-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ITEM_SEQ', models.IntegerField(null=True)),
                ('ITEM_NAME', models.CharField(default='', max_length=200, null=True)),
                ('ITEM_NAME_SUB', models.TextField(blank=True, default='', null=True)),
                ('ENTP_NAME', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('CHART', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('PRINT_FRONT', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('PRINT_BACK', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('DRUG_SHAPE', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('DRUG_SHAPE2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('COLOR_CLASS1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('COLOR_CLASS1_투명_제외', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('COLOR_CLASS2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('COLOR_CLASS2_투명_제외', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('LINE_FRONT', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('LINE_BACK', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('LENG_LONG', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('LENG_SHORT', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('THICK', models.CharField(default='', max_length=50, null=True)),
                ('CLASS_NAME', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ETC_OTC_NAME', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('FORM_CODE_NAME', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('MARK_CODE_FRONT_ANAL', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('MARK_CODE_BACK_ANAL', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('MARK_CODE_FRONT_IMG', models.TextField(blank=True, default='', null=True)),
                ('MARK_CODE_BACK_IMG', models.TextField(blank=True, default='', null=True)),
                ('MARK_CODE_FRONT', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('MARK_CODE_BACK', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
            options={
                'db_table': 'drug_info',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_files', models.ImageField(blank=True, upload_to='Uploaded Files/%y/%m/%d/', verbose_name='file')),
                ('predict_shape', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('predict_color', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('pub_date', models.DateField(auto_now=True)),
                ('result', models.CharField(blank=True, default='', max_length=5000, null=True)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_result', models.CharField(blank=True, default='', max_length=5000)),
                ('label', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
