# Generated by Django 4.1.6 on 2023-02-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_druginfoefcy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='druginfoefcy',
            old_name='atpn_esitm',
            new_name='atpnQesitm',
        ),
        migrations.RenameField(
            model_name='druginfoefcy',
            old_name='atpn_warn',
            new_name='atpnWarnQesitm',
        ),
        migrations.RenameField(
            model_name='druginfoefcy',
            old_name='deposit',
            new_name='depositMethodQesitm',
        ),
        migrations.RenameField(
            model_name='druginfoefcy',
            old_name='efcy',
            new_name='efcyQesitm',
        ),
        migrations.RenameField(
            model_name='druginfoefcy',
            old_name='en_name',
            new_name='entpName',
        ),
        migrations.RenameField(
            model_name='druginfoefcy',
            old_name='intrc_esitm',
            new_name='intrcQesitm',
        ),
        migrations.RenameField(
            model_name='druginfoefcy',
            old_name='item_name',
            new_name='itemName',
        ),
        migrations.RenameField(
            model_name='druginfoefcy',
            old_name='item_seq',
            new_name='itemSeq',
        ),
        migrations.RenameField(
            model_name='druginfoefcy',
            old_name='se_esitm',
            new_name='seQesitm',
        ),
        migrations.RenameField(
            model_name='druginfoefcy',
            old_name='use_method',
            new_name='useMethodQesitm',
        ),
    ]
