# Generated by Django 4.1.6 on 2023-02-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_drugmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugmaterial',
            name='BAR_CODE',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='CANCEL_DATE',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='CANCEL_NAME',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='CHANGE_DATE',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='CHART',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='CLASS_NO',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='EDI_CODE',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='EE_DOC_ID',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='ENTP_NAME',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='ETC_OTC_CODE',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='INSERT_FILE',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='ITEM_NAME',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='ITEM_PERMIT_DATE',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='ITEM_SEQ',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='MATERIAL_NAME',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='NB_DOC_ID',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='PACK_UNIT',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='REEXAM_DATE',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='REEXAM_TARGET',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='STORAGE_METHOD',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='TYPE_CODE',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='TYPE_NAME',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='UD_DOC_ID',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaterial',
            name='VALID_TERM',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
