# Generated by Django 4.1.6 on 2023-02-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_druginfo_chart_alter_druginfo_class_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='druginfo',
            name='EDI_CODE',
        ),
    ]
