# Generated by Django 4.1.6 on 2023-02-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_druginfo_mark_code_back_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginfo',
            name='CLASS_NAME',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='COLOR_CLASS1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='COLOR_CLASS1_투명_제외',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='COLOR_CLASS2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='COLOR_CLASS2_투명_제외',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='DRUG_SHAPE',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='DRUG_SHAPE2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='ENTP_NAME',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='ETC_OTC_NAME',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='FORM_CODE_NAME',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='ITEM_NAME',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='ITEM_NAME_SUB',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='LENG_LONG',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='LENG_SHORT',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='LINE_BACK',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='LINE_FRONT',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='MARK_CODE_BACK',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='MARK_CODE_BACK_ANAL',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='MARK_CODE_FRONT',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='MARK_CODE_FRONT_ANAL',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='PRINT_BACK',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='PRINT_FRONT',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
