# Generated by Django 4.1.6 on 2023-02-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_druginfo_class_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='predict',
            new_name='predict_color',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='predict_shape',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
