# Generated by Django 4.1.6 on 2023-02-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_druginfo_edi_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginfo',
            name='CHART',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
