# Generated by Django 4.1.6 on 2023-02-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_druginfo_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginfo',
            name='MARK_CODE_BACK_IMG',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='MARK_CODE_FRONT_IMG',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
